# import 
from __future__ import print_function
import os
import sys
import shutil
import glob
from subprocess import Popen, PIPE

def export_conda_envs(config):
    """
    Export conda env yaml files
    """
    # export==True? 
    try:
        if not is_true(config['pipeline']['export_conda']):
            return None
    except KeyError:
        return None
    sys.stderr.write('\33[36m--- Exporting conda envs ---\x1b[0m\n')
    # base dir
    try:
        d = config['pipeline']['snakemake_folder']
    except KeyError:
        msg = '\33[33m WARNING: Could not find "snakemake_folder" in config \x1b[0m\n'
        sys.stderr.write(msg)
        return None
    # output dir
    try:
        outd = config['output_dir']
    except KeyError:
        msg = '\33[33m WARNING: Could not find "output_dir" in config \x1b[0m\n'
        sys.stderr.write(msg)
        return None
    outd = os.path.join(outd, 'conda_envs')
    if not os.path.isdir(outd):
        os.makedirs(outd)
    # conda env dir
    d = os.path.join(d, '.snakemake', 'conda')
    if not os.path.isdir(d):
        msg = '\33[33m WARNING: Could not find: {} \x1b[0m\n'
        sys.stderr.write(msg.format(d))
        msg = '\33[33m   conda env yaml files will not be exported \x1b[0m\n'
        sys.stderr.write(msg)
        return None
    # conda envs
    for F in glob.glob(os.path.join(d, '*.yaml')):
        conda_path = os.path.splitext(F)[0]
        if os.path.isdir(conda_path):
            cmd = ['conda', 'env', 'export', '-p', conda_path]
            p = Popen(cmd, stdout=PIPE)
            output, err = p.communicate()
            rc = p.returncode
            if rc != 0:
                msg = '\33[33m  could not export env: {}\x1b[0m\n'
                sys.stderr.write(msg.format(conda_path))
                continue
            # writing env
            outfile = os.path.join(outd, os.path.split(F)[1])
            with open(outfile, 'w') as outF:
                for line in output.decode().split('\n'):
                    outF.write(line + '\n')
    msg = '\33[33m Conda env yaml files written to: {} \x1b[0m\n'
    sys.stderr.write(msg.format(outd))
    return None
        
